// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// TxnStatusResponse txn status response
// Example: {"status-response":{"fa":"test","reference_id":"test","status":"SUCC","timestamp":"test"}}
//
// swagger:model TxnStatusResponse
type TxnStatusResponse []interface{}

// Validate validates this txn status response
func (m TxnStatusResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this txn status response based on context it is used
func (m TxnStatusResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
