// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AccountProviderInfo Store of value account provider info
//
// swagger:model AccountProviderInfo
type AccountProviderInfo struct {

	// Additional info, if any
	// Max Length: 999
	AdditionalInfo string `json:"additional_info,omitempty"`

	// code to identify the entity like bank, prepaid card/voucher issuing system, etc.,
	// Example: GTBIRWRKXXX
	// Required: true
	Code *string `json:"code"`

	// entity name like bank name, prepaid card/voucher issuing system, etc.,
	// Example: GT Bank Rawanda
	// Required: true
	Name *string `json:"name"`

	// sub code like entity's branch code, etc.,
	Subcode string `json:"subcode,omitempty"`
}

// Validate validates this account provider info
func (m *AccountProviderInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAdditionalInfo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccountProviderInfo) validateAdditionalInfo(formats strfmt.Registry) error {
	if swag.IsZero(m.AdditionalInfo) { // not required
		return nil
	}

	if err := validate.MaxLength("additional_info", "body", m.AdditionalInfo, 999); err != nil {
		return err
	}

	return nil
}

func (m *AccountProviderInfo) validateCode(formats strfmt.Registry) error {

	if err := validate.Required("code", "body", m.Code); err != nil {
		return err
	}

	return nil
}

func (m *AccountProviderInfo) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this account provider info based on context it is used
func (m *AccountProviderInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AccountProviderInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountProviderInfo) UnmarshalBinary(b []byte) error {
	var res AccountProviderInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
