// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// PersonID <br> 1. Beneficiary id is case insensitve normative represenation as id-type:id@provider <br> 2. This will enumerate foundational and functioanl id's to easily resolvable addressess <br> 3. This property is intended to unambiguously refer to an object, such as a person, organization, etc., <br> 4. Few examples: <br> - id@identifier-type.id-provider e.g token:12345@mosip, vid:12345@philid <br> - id@civil-registry.issuing-agency e.g id:12345@rwanda, id:12345@ejanma.karnataka <br> - id@functional-identifier.issuing-agency e.g id:12345@voter.Rwanda, id:12345@DL.karnataka, mobile:12345@fruits.karnataka <br> Note: id provider should be made configurable and solutions should adapt to the local jurisdiction and policies.<br> e.g fruits.karnataka represents farmer registry in karnataka state govt.<br>
// Example: vid:12345@mosip
//
// swagger:model PersonId
type PersonID string

// Validate validates this person Id
func (m PersonID) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this person Id based on context it is used
func (m PersonID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
