// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// TransactionID Unique transaction_id set by txn initiating system (i.e sender) to co-relate requests across processing systems/service end points
// Example: 12345678901234567000
//
// swagger:model TransactionId
type TransactionID string

// Validate validates this transaction Id
func (m TransactionID) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.MaxLength("", "body", string(m), 99); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this transaction Id based on context it is used
func (m TransactionID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
