// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TxnStatusRequest Request to search disbursement using payer or payee fa
//
// swagger:model TxnStatusRequest
type TxnStatusRequest struct {

	// locale
	Locale LanguageCode `json:"locale,omitempty"`

	// reference id
	// Required: true
	ReferenceID *ReferenceID `json:"reference_id"`

	// request type
	// Enum: [link unlink update resolve]
	RequestType string `json:"request_type,omitempty"`

	// search attribute
	// Required: true
	SearchAttribute interface{} `json:"search_attribute"`

	// search type
	// Required: true
	// Enum: [transaction_id reference_id_list]
	SearchType *string `json:"search_type"`
}

// Validate validates this txn status request
func (m *TxnStatusRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLocale(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReferenceID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRequestType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSearchAttribute(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSearchType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TxnStatusRequest) validateLocale(formats strfmt.Registry) error {
	if swag.IsZero(m.Locale) { // not required
		return nil
	}

	if err := m.Locale.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("locale")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("locale")
		}
		return err
	}

	return nil
}

func (m *TxnStatusRequest) validateReferenceID(formats strfmt.Registry) error {

	if err := validate.Required("reference_id", "body", m.ReferenceID); err != nil {
		return err
	}

	if err := validate.Required("reference_id", "body", m.ReferenceID); err != nil {
		return err
	}

	if m.ReferenceID != nil {
		if err := m.ReferenceID.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("reference_id")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("reference_id")
			}
			return err
		}
	}

	return nil
}

var txnStatusRequestTypeRequestTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["link","unlink","update","resolve"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		txnStatusRequestTypeRequestTypePropEnum = append(txnStatusRequestTypeRequestTypePropEnum, v)
	}
}

const (

	// TxnStatusRequestRequestTypeLink captures enum value "link"
	TxnStatusRequestRequestTypeLink string = "link"

	// TxnStatusRequestRequestTypeUnlink captures enum value "unlink"
	TxnStatusRequestRequestTypeUnlink string = "unlink"

	// TxnStatusRequestRequestTypeUpdate captures enum value "update"
	TxnStatusRequestRequestTypeUpdate string = "update"

	// TxnStatusRequestRequestTypeResolve captures enum value "resolve"
	TxnStatusRequestRequestTypeResolve string = "resolve"
)

// prop value enum
func (m *TxnStatusRequest) validateRequestTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, txnStatusRequestTypeRequestTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *TxnStatusRequest) validateRequestType(formats strfmt.Registry) error {
	if swag.IsZero(m.RequestType) { // not required
		return nil
	}

	// value enum
	if err := m.validateRequestTypeEnum("request_type", "body", m.RequestType); err != nil {
		return err
	}

	return nil
}

func (m *TxnStatusRequest) validateSearchAttribute(formats strfmt.Registry) error {

	if m.SearchAttribute == nil {
		return errors.Required("search_attribute", "body", nil)
	}

	return nil
}

var txnStatusRequestTypeSearchTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["transaction_id","reference_id_list"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		txnStatusRequestTypeSearchTypePropEnum = append(txnStatusRequestTypeSearchTypePropEnum, v)
	}
}

const (

	// TxnStatusRequestSearchTypeTransactionID captures enum value "transaction_id"
	TxnStatusRequestSearchTypeTransactionID string = "transaction_id"

	// TxnStatusRequestSearchTypeReferenceIDList captures enum value "reference_id_list"
	TxnStatusRequestSearchTypeReferenceIDList string = "reference_id_list"
)

// prop value enum
func (m *TxnStatusRequest) validateSearchTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, txnStatusRequestTypeSearchTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *TxnStatusRequest) validateSearchType(formats strfmt.Registry) error {

	if err := validate.Required("search_type", "body", m.SearchType); err != nil {
		return err
	}

	// value enum
	if err := m.validateSearchTypeEnum("search_type", "body", *m.SearchType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this txn status request based on the context it is used
func (m *TxnStatusRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLocale(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateReferenceID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TxnStatusRequest) contextValidateLocale(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Locale.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("locale")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("locale")
		}
		return err
	}

	return nil
}

func (m *TxnStatusRequest) contextValidateReferenceID(ctx context.Context, formats strfmt.Registry) error {

	if m.ReferenceID != nil {
		if err := m.ReferenceID.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("reference_id")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("reference_id")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TxnStatusRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TxnStatusRequest) UnmarshalBinary(b []byte) error {
	var res TxnStatusRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
